spring:
  application:
    name: user

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seata_client?useInformationSchema=true
    username: root
    password: abcd1234
    # mysql 5 driver
    # driver-class-name: com.mysql.jdbc.Driver
    # mysql 8 driver
    driver-class-name: com.mysql.cj.jdbc.Driver